import os
from app import app, db
from app.models import User, Post, Player, Polls, PollVote, PollPlayer

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = \
    'sqlite:///' + os.path.join(basedir, 'app.db')

User.query.delete()
Player.query.delete()
Polls.query.delete()
PollVote.query.delete()
PollPlayer.query.delete()

#create users
u1 = User(id='00000001', username = 'Hasi', email = 'hasi@test.com', admin = True)
u2 = User(id='00000002', username = 'Sam', email = 'sam@test.com', admin = True)
u3 = User(id='00000003', username = 'Tim', email = 'tim@test.com', admin = True)
u4 = User(id='00000004', username = 'Tom', email = 'Tom@test.com', admin = False)
u5 = User(id='00000005', username = 'Michael', email = 'Michael@test.com', admin = False)
u6 = User(id='00000006', username = 'John', email = 'John@test.com', admin = False)
u7 = User(id='00000007', username = 'Susan', email = 'Susan@test.com', admin = False)
u8 = User(id='00000008', username = 'Rachel', email = 'Rachel@test.com', admin = False)
u9 = User(id='00000009', username = 'Chris', email = 'Chris@test.com', admin = False)

db.session.add(u1)
db.session.add(u2)
db.session.add(u3)
db.session.add(u4)
db.session.add(u5)
db.session.add(u6)
db.session.add(u7)
db.session.add(u8)
db.session.add(u9)
u1.set_password('Hasitest1')
u2.set_password('Samtest1')
u3.set_password('Timtest1')
u4.set_password('Tomtest1')
u5.set_password('Michaeltest1')
u6.set_password('Johntest1')
u7.set_password('Susantest1')
u8.set_password('Racheltest1')
u9.set_password('Christest1')

#create Players
p1 = Player(playerid = '1', playername='Luka Modric', nationality = 'Croatia', club = 'Real Madrid')
p2 = Player(playerid = '2', playername='Cristiano Ronaldo', nationality = 'Portugal', club = 'Juventus')
p3 = Player(playerid = '3', playername='Lionel Messi', nationality = 'Argentina', club = 'Barcelona')
p4 = Player(playerid = '4', playername='Kylian Mbappé', nationality = 'France', club = 'Paris St-Germain')
p5 = Player(playerid = '5', playername='Mohamed Salah', nationality = 'Egypt', club = 'Liverpool')
p6 = Player(playerid = '6', playername='Antoine Griezmann', nationality = 'France', club = 'Atletico Madrid')
p7 = Player(playerid = '7', playername='Eden Hazard', nationality = 'Belgium', club = 'Chelsea')
p8 = Player(playerid = '8', playername='Kevin De Bruyne', nationality = 'Belgium', club = 'Manchester City')
p9 = Player(playerid = '9', playername='Harry Kane', nationality = 'England', club = 'Tottenham Hotspur')
p10 = Player(playerid = '10', playername='NGolo Kanté', nationality = 'France', club = 'Chelsea')
p11 = Player(playerid = '11', playername='Neymar', nationality = 'Brazil', club = 'Paris St-Germain')
p12 = Player(playerid = '12', playername='Raphaël Varane', nationality = 'France', club = 'Real Madrid')
p13 = Player(playerid = '13', playername='Ivan Rakitic', nationality = 'Croatia', club = 'Barcelona')
p14 = Player(playerid = '14', playername='Luis Suárez', nationality = 'Uruguay', club = 'Barcelona')
p15 = Player(playerid = '15', playername='Sergio Agüero', nationality = 'Argentina', club = 'Manchester City')
p16 = Player(playerid = '16', playername='Paul Pogba', nationality = 'France', club = 'Manchester United')
p17 = Player(playerid = '17', playername='Sergio Ramos', nationality = 'Spain', club = 'Real Madrid')
p18 = Player(playerid = '18', playername='Marcelo', nationality = 'Brazil', club = 'Real Madrid')
p19 = Player(playerid = '19', playername='Sadio Mané', nationality = 'Senegal', club = 'Liverpool')
p20 = Player(playerid = '20', playername='David Silva', nationality = 'Spain', club = 'Manchester City')


db.session.add(p1)
db.session.add(p2)
db.session.add(p3)
db.session.add(p4)
db.session.add(p5)
db.session.add(p6)
db.session.add(p7)
db.session.add(p8)
db.session.add(p9)
db.session.add(p10)
db.session.add(p11)
db.session.add(p12)
db.session.add(p13)
db.session.add(p14)
db.session.add(p15)
db.session.add(p16)
db.session.add(p17)
db.session.add(p18)
db.session.add(p19)
db.session.add(p20)


#createPolls
po1= Polls(pollid='1', pollname='Best Barca Player', creatorid='00000001')
po2= Polls(pollid='2', pollname='Best Player', creatorid='00000002')
po3= Polls(pollid='3', pollname='Best Player #2', creatorid='00000005')
db.session.add(po1)
db.session.add(po2)
db.session.add(po3)

#startvoting
pv1= PollVote(voteid='1', userid='00000002', pollid='1', playerid='01')
pv2= PollVote(voteid='2', userid='00000004', pollid='1', playerid='01')
pv3= PollVote(voteid='3', userid='00000005', pollid='1', playerid='04')

pv4= PollVote(voteid='4', userid='00000006', pollid='2', playerid='02')
pv5= PollVote(voteid='5', userid='00000002', pollid='2', playerid='03')
pv6= PollVote(voteid='6', userid='00000001', pollid='2', playerid='04')

pv7= PollVote(voteid='7', userid='00000002', pollid='3', playerid='01')
pv8= PollVote(voteid='8', userid='00000003', pollid='3', playerid='04')
pv9= PollVote(voteid='9', userid='00000001', pollid='3', playerid='02')
db.session.add(pv1)
db.session.add(pv2)
db.session.add(pv3)
db.session.add(pv4)
db.session.add(pv5)
db.session.add(pv6)
db.session.add(pv7)
db.session.add(pv8)
db.session.add(pv9)

#count votes
pp1 = PollPlayer(pollplayerid ='1', pollid='1', playerid='1', votecount ='2')
pp2 = PollPlayer(pollplayerid ='2', pollid='1', playerid='4', votecount ='1')
pp3 = PollPlayer(pollplayerid ='3', pollid='1', playerid='2', votecount ='0')

pp4 = PollPlayer(pollplayerid ='4', pollid='2', playerid='6', votecount ='1')
pp5 = PollPlayer(pollplayerid ='5', pollid='2', playerid='7', votecount ='1')
pp6 = PollPlayer(pollplayerid ='6', pollid='2', playerid='9', votecount ='1')

pp7 = PollPlayer(pollplayerid ='7', pollid='3', playerid='12', votecount ='1')
pp8 = PollPlayer(pollplayerid ='8', pollid='3', playerid='15', votecount ='1')
pp9 = PollPlayer(pollplayerid ='9', pollid='3', playerid='19', votecount ='1')

db.session.add(pp1)
db.session.add(pp2)
db.session.add(pp3)
db.session.add(pp4)
db.session.add(pp5)
db.session.add(pp6)
db.session.add(pp7)
db.session.add(pp8)
db.session.add(pp9)


db.session.commit()    