"""added pollplayer

Revision ID: 52051cbe08e6
Revises: 74ce3a61ac36
Create Date: 2019-05-15 11:50:08.624026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52051cbe08e6'
down_revision = '74ce3a61ac36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_player',
    sa.Column('pollplayerid', sa.Integer(), nullable=False),
    sa.Column('pollid', sa.Integer(), nullable=True),
    sa.Column('playerid', sa.Integer(), nullable=True),
    sa.Column('votecount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playerid'], ['player.playerid'], ),
    sa.ForeignKeyConstraint(['pollid'], ['polls.pollid'], ),
    sa.PrimaryKeyConstraint('pollplayerid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_player')
    # ### end Alembic commands ###
