"""first

Revision ID: 74ce3a61ac36
Revises: 
Create Date: 2019-05-14 23:37:24.592766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ce3a61ac36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('playerid', sa.Integer(), nullable=False),
    sa.Column('playername', sa.String(length=128), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('club', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('playerid')
    )
    op.create_index(op.f('ix_player_club'), 'player', ['club'], unique=False)
    op.create_index(op.f('ix_player_nationality'), 'player', ['nationality'], unique=False)
    op.create_index(op.f('ix_player_playername'), 'player', ['playername'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('polls',
    sa.Column('pollid', sa.Integer(), nullable=False),
    sa.Column('pollname', sa.String(length=64), nullable=True),
    sa.Column('creatorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creatorid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pollid')
    )
    op.create_index(op.f('ix_polls_pollname'), 'polls', ['pollname'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('poll_vote',
    sa.Column('voteid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('pollid', sa.Integer(), nullable=True),
    sa.Column('playerid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playerid'], ['player.playerid'], ),
    sa.ForeignKeyConstraint(['pollid'], ['polls.pollid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('voteid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_vote')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_polls_pollname'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_player_playername'), table_name='player')
    op.drop_index(op.f('ix_player_nationality'), table_name='player')
    op.drop_index(op.f('ix_player_club'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
