"""added poll, pollvote, players

Revision ID: 8889dc7b620a
Revises: 6b6069587459
Create Date: 2019-05-12 18:04:08.769722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8889dc7b620a'
down_revision = '6b6069587459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('playerid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('club', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('playerid')
    )
    op.create_index(op.f('ix_player_club'), 'player', ['club'], unique=False)
    op.create_index(op.f('ix_player_firstname'), 'player', ['firstname'], unique=False)
    op.create_index(op.f('ix_player_lastname'), 'player', ['lastname'], unique=False)
    op.create_index(op.f('ix_player_nationality'), 'player', ['nationality'], unique=False)
    op.create_table('poll',
    sa.Column('pollid', sa.Integer(), nullable=False),
    sa.Column('creatorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creatorid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pollid')
    )
    op.create_table('poll_vote',
    sa.Column('voteid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('pollid', sa.Integer(), nullable=True),
    sa.Column('playerid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playerid'], ['player.playerid'], ),
    sa.ForeignKeyConstraint(['pollid'], ['poll.pollid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('voteid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_vote')
    op.drop_table('poll')
    op.drop_index(op.f('ix_player_nationality'), table_name='player')
    op.drop_index(op.f('ix_player_lastname'), table_name='player')
    op.drop_index(op.f('ix_player_firstname'), table_name='player')
    op.drop_index(op.f('ix_player_club'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
