"""removed poll table, added Polls

Revision ID: df20059f0239
Revises: 8889dc7b620a
Create Date: 2019-05-14 13:05:26.139456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df20059f0239'
down_revision = '8889dc7b620a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('pollid', sa.Integer(), nullable=False),
    sa.Column('pollname', sa.String(length=64), nullable=True),
    sa.Column('creatorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creatorid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pollid')
    )
    op.create_index(op.f('ix_polls_pollname'), 'polls', ['pollname'], unique=False)
    op.drop_table('poll')
    op.create_unique_constraint(None, 'player', ['firstname', 'lastname'])
    op.drop_constraint(None, 'poll_vote', type_='foreignkey')
    op.create_foreign_key(None, 'poll_vote', 'polls', ['pollid'], ['pollid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll_vote', type_='foreignkey')
    op.create_foreign_key(None, 'poll_vote', 'poll', ['pollid'], ['pollid'])
    op.drop_constraint(None, 'player', type_='unique')
    op.create_table('poll',
    sa.Column('pollid', sa.INTEGER(), nullable=False),
    sa.Column('creatorid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['creatorid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pollid')
    )
    op.drop_index(op.f('ix_polls_pollname'), table_name='polls')
    op.drop_table('polls')
    # ### end Alembic commands ###
